### ISSUE TITLE
unresolved external symbol in building qdevicewatcher

### ISSUE THREAD

**Issue by Seakia** [wang-bin/qdevicewatcher#10]
Hello,

I am confused with this point that I use qt5.5.1_msvc_32bit to build qdevicewatcher, But it happens unresolved external symbol about windows function, such as:

Creating library ..\out\lib_win_\QDeviceWatcherd2.lib and object ..\out\lib_win_\QDeviceWatcherd2.exp
qdevicewatcher_win32.obj : error LNK2019: unresolved external symbol __imp__DefWindowProcW@16 referenced in function "long __stdcall dw_internal_proc(struct HWND__ *,unsigned int,unsigned int,long)" (?dw_internal_proc@@YGJPAUHWND__@@IIJ@Z)
qdevicewatcher_win32.obj : error LNK2019: unresolved external symbol __imp__RegisterClassW@4 referenced in function "struct HWND__ * __cdecl dw_create_internal_window(void const *)" (?dw_create_internal_window@@YAPAUHWND__@@PBX@Z)
qdevicewatcher_win32.obj : error LNK2019: unresolved external symbol __imp__UnregisterClassW@8 referenced in function "void __cdecl dw_destroy_internal_window(struct HWND__ *)" (?dw_destroy_internal_window@@YAXPAUHWND__@@@Z)
qdevicewatcher_win32.obj : error LNK2019: unresolved external symbol __imp__CreateWindowExW@48 referenced in function "struct HWND__ * __cdecl dw_create_internal_window(void const *)" (?dw_create_internal_window@@YAPAUHWND__@@PBX@Z)
qdevicewatcher_win32.obj : error LNK2019: unresolved external symbol __imp__DestroyWindow@4 referenced in function "void __cdecl dw_destroy_internal_window(struct HWND__ *)" (?dw_destroy_internal_window@@YAXPAUHWND__@@@Z)
qdevicewatcher_win32.obj : error LNK2019: unresolved external symbol __imp__GetWindowLongW@8 referenced in function "long __stdcall dw_internal_proc(struct HWND__ *,unsigned int,unsigned int,long)" (?dw_internal_proc@@YGJPAUHWND__@@IIJ@Z)
qdevicewatcher_win32.obj : error LNK2019: unresolved external symbol __imp__SetWindowLongW@12 referenced in function "struct HWND__ * __cdecl dw_create_internal_window(void const *)" (?dw_create_internal_window@@YAPAUHWND__@@PBX@Z)
..\out\lib_win_\QDeviceWatcherd2.dll : fatal error LNK1120: 7 unresolved externals

it points to windows function, Do I need to make some setting before build this project?

**Comment by Seakia** [comment]
And Should I set "Build Environment" in the Qt Creator to add include directory and lib directory?  Thank you.

**Comment by Seakia** [comment]
my friends help me to solve this problem, his solution is add the corresponding missing lib in the "libQDeviceWatcher.pro", Do you have one idea about this phenomenon?

**Comment by wang-bin** [comment]
I'm not sure. I haven't build it for a long time. now it should be fixed
