### ISSUE TITLE
QDevicewatcher does not build on Linux

### ISSUE THREAD

**Issue by nerdoc** [wang-bin/qdevicewatcher#5]
I just tried to build the QDevicewatcher test app under Ubuntu 14.04, and it does not compile.
It seems that you use a mac for development, could that be true? Because I think that mac specific code is not removed by an #ifdef by the preprocessor - so it gets compiled under Linux as well and then the compiler doesn't find CoreServices.h and IOCDMedia.h + IODVDMedia.h

Did you try to compile the software/lib under Linux recently?

**Comment by wang-bin** [comment]
Long time ago. Try latest code please. Should be fine now

**Comment by nerdoc** [comment]
I used git HEAD...

**Comment by nerdoc** [comment]
Aaah. You updated the code already... I'll try ASAP.

**Comment by nerdoc** [comment]
Works perfectly, thanks. I'll close this if you don't mind.
