### ISSUE TITLE
Missing header file - compiling on windows

### ISSUE THREAD

**Issue by Xsmael** [wang-bin/qdevicewatcher#6]
#include <CoreServices/CoreServices.h>
    #include <IOKit/storage/IOCDMedia.h>
    #include <IOKit/storage/IODVDMedia.h>

Where can I get these files? I'm trying to compile but they are missing.
I'm copiling on windows are they needed only for mac ? if so how can I compile the project on windows avoiding the compiler to complain for that ?

**Comment by wang-bin** [comment]
Try latest code please. Should be fine now

**Comment by Xsmael** [comment]
Thanks! it works now indeed. could you tell me please what was the problem ?

**Comment by wang-bin** [comment]
that file is only built for mac, not windows
