### ISSUE TITLE
Bind: Address Already in Use

### ISSUE THREAD

**Issue by jurismai** [wang-bin/qdevicewatcher#7]
Your app compiles and runs fine. When I try to integrate the lib into my app I get "Bind: Address Already in Use". I tried to set SO_REUSEADDR as suggested here:

http://hea-www.harvard.edu/~fine/Tech/addrinuse.html

This did not help. I have integrated the files 

qdevicewatcher.h
qdevicewatcher_p.h
qdevicewatcher.cpp
qdevicewatcher_linux.cpp

directly, not as a lib. My app builds without errors, but I get the bind() errormessage. Is there any idea how to overcome this issue?

Thanks in advance

**Comment by wang-bin** [comment]
i have no idea

**Comment by wang-bin** [comment]
should be fixed in e223a2b
